spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
  profiles:
    active: dev
  data:
    rest:
      base-path: rest
logging.level.org.hibernate:
  type.descriptor.sql.BasicBinder: TRACE